table Customer
	lineageTag: 8c8878ed-b91f-4a98-acf0-9f6e7e24a085

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: d5002eff-eaec-4a1a-b4ba-1330e4bd51a9
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: c1a42822-38e5-4b5d-900f-a189c4b9eb50
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: fd516544-f955-4626-a111-2feecb7be626
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column FullName
		dataType: string
		lineageTag: b499cdb1-bb26-42f6-a37c-b6837a9d5919
		summarizeBy: none
		sourceColumn: FullName

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 29e7dcd8-8cec-47f9-928f-128383b5f87f
		summarizeBy: none
		sourceColumn: BirthDate

		annotation SummarizationSetBy = Automatic

	column MaritalStatus
		dataType: string
		lineageTag: 677c637b-9e0c-4597-ad07-8ae103d6dc56
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 970124d6-55c4-4ebb-bc1e-96466856dcd1
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column YearlyIncome
		dataType: int64
		formatString: 0
		lineageTag: 85130b97-ebfc-4e36-b126-82b3cc62fa19
		summarizeBy: none
		sourceColumn: YearlyIncome

		annotation SummarizationSetBy = Automatic

	column TotalChildren
		dataType: int64
		formatString: 0
		lineageTag: 933d4d0c-da21-475d-968a-fa42b2c83765
		summarizeBy: none
		sourceColumn: TotalChildren

		annotation SummarizationSetBy = Automatic

	column NumberChildrenAtHome
		dataType: int64
		formatString: 0
		lineageTag: b24106c5-bdba-444a-bba1-3c40e405835f
		summarizeBy: none
		sourceColumn: NumberChildrenAtHome

		annotation SummarizationSetBy = Automatic

	column Education
		dataType: string
		lineageTag: 249d756d-d696-48ab-903b-fb211f936b7d
		summarizeBy: none
		sourceColumn: Education

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: e604148a-5ad5-43f0-a541-2df60b485289
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column HouseOwnerFlag
		dataType: int64
		formatString: 0
		lineageTag: b8d5dae0-ca6b-425d-8ab6-4b59cf37b6d2
		summarizeBy: none
		sourceColumn: HouseOwnerFlag

		annotation SummarizationSetBy = Automatic

	column NumberCarsOwned
		dataType: int64
		formatString: 0
		lineageTag: d670c998-ce49-47d8-a1b3-55b6101ad8ea
		summarizeBy: none
		sourceColumn: NumberCarsOwned

		annotation SummarizationSetBy = Automatic

	column AddressLine1
		dataType: string
		lineageTag: 0f428eb9-2786-4f95-9ce2-e0ca2cb3fcb0
		summarizeBy: none
		sourceColumn: AddressLine1

		annotation SummarizationSetBy = Automatic

	column DateFirstPurchase
		dataType: dateTime
		formatString: General Date
		lineageTag: f5f8f229-2296-4537-8095-4389ffa46c25
		summarizeBy: none
		sourceColumn: DateFirstPurchase

		annotation SummarizationSetBy = Automatic

	column CommuteDistance
		dataType: string
		lineageTag: aa243eb6-bfb8-4886-a2b0-67905a09f7b5
		summarizeBy: none
		sourceColumn: CommuteDistance

		annotation SummarizationSetBy = Automatic

	partition Customer-cfd3aae7-1e76-467c-a4ce-8f9c9b91057c = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Sukumar Bera\OneDrive\Documents\Personal Files\Microsoft Power BI\00_Data Files\04_AdventureWorks\AdventureWorks_Database.xlsx"), null, true),
				    Customer_Table = Source{[Item="Customer",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Customer_Table,{{"CustomerKey", Int64.Type}, {"FirstName", type text}, {"LastName", type text}, {"FullName", type text}, {"BirthDate", type datetime}, {"MaritalStatus", type text}, {"Gender", type text}, {"YearlyIncome", Int64.Type}, {"TotalChildren", Int64.Type}, {"NumberChildrenAtHome", Int64.Type}, {"Education", type text}, {"Occupation", type text}, {"HouseOwnerFlag", Int64.Type}, {"NumberCarsOwned", Int64.Type}, {"AddressLine1", type text}, {"DateFirstPurchase", type datetime}, {"CommuteDistance", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

